# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive

# Miscellaneous
google_analytics: UA-35413718-1
favicon: /favicon.ico
twitter: flypiggy
google_plus:
